"""Style-guide scaffolding (cg init-styleguide).

Generates four artifacts derived from the CURRENT audit of the project, so the
documented conventions match observed reality rather than generic defaults:

1. ``.editorconfig``          - editor-level whitespace/indent rules
2. ``.pre-commit-config.yaml`` - hygiene hooks + the project's own formatter
3. ``.cg/ci-lint.yml``        - CI lint job snippet (copy into .github/workflows/)
4. ``STYLEGUIDE.md``          - short human-readable style guide with drift counts

Builders are pure (no I/O beyond optional version detection); writing is a
separate step so existing files can be skipped or overwritten with --force.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from collections import Counter
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

from conventionguardian.diff import unified_diff
from conventionguardian.models import Category, Finding, ToolProfile


@dataclass
class StyleguidePlan:
    """Artifacts to write: relative path -> content, plus derivation notes."""

    artifacts: dict[str, str] = field(default_factory=dict)
    existed: dict[str, bool] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)


@dataclass
class DriftReport:
    """Result of a --check run: which artifacts match, drift, or aren't armed."""

    ok: list[str] = field(default_factory=list)
    drifted: list[str] = field(default_factory=list)
    not_armed: list[str] = field(default_factory=list)
    diffs: dict[str, str] = field(default_factory=dict)

    @property
    def clean(self) -> bool:
        return not self.drifted


# --------------------------------------------------------------- helpers ----


def _files_with(findings: list[Finding], fix_id: str) -> int:
    """Number of distinct files carrying a finding with this fix_id."""
    return len({f.path for f in findings if f.fix_id == fix_id})


def _quote_direction(qfindings: list[Finding]) -> str | None:
    counts = Counter(f.recommended for f in qfindings if f.recommended)
    return counts.most_common(1)[0][0] if counts else None


def _detect_version(tool: str) -> str | None:
    """Best-effort `tool --version` parse; None when missing or unparseable."""
    found = shutil.which(tool)
    if not found:
        return None
    try:
        res = subprocess.run(
            [found, "--version"], capture_output=True, text=True, timeout=10
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    out = (res.stdout or "").strip() or (res.stderr or "").strip()
    for tok in reversed(out.replace(",", " ").split()):
        if tok and tok[0].isdigit():
            return tok
    return None


# ---------------------------------------------------------- .editorconfig ---


def _editorconfig(profile: ToolProfile, files: list[Path], findings: list[Finding]) -> str:
    langs = set(profile.languages)
    exts = {p.suffix for p in files}
    crlf = _files_with(findings, "misc-crlf")
    lines = [
        "# Generated by ConventionGuardian (cg init-styleguide). Review before committing.",
        "root = true",
        "",
        "[*]",
        "charset = utf-8",
    ]
    if crlf:
        lines.append(f"# cg: {crlf} file(s) still use CRLF; normalize to LF")
    lines += [
        "end_of_line = lf",
        "insert_final_newline = true",
        "trim_trailing_whitespace = true",
        "",
    ]
    if "Python" in langs:
        lines += ["[*.py]", "indent_style = space", "indent_size = 4",
                  "max_line_length = 100", ""]
    if langs & {"JavaScript", "TypeScript"}:
        lines += ["[*.{js,jsx,mjs,cjs,ts,tsx}]", "indent_style = space",
                  "indent_size = 2", ""]
    if exts & {".css", ".scss", ".less", ".html", ".json", ".yaml", ".yml", ".md"}:
        lines += ["[*.{css,scss,less,html,json,yaml,yml,md}]", "indent_style = space",
                  "indent_size = 2", ""]
    if "Go" in langs:
        lines += ["[*.go]", "indent_style = tab", ""]
    if "Rust" in langs:
        lines += ["[*.rs]", "indent_style = space", "indent_size = 4", ""]
    if any(p.name == "Makefile" for p in files):
        lines += ["[Makefile]", "indent_style = tab", ""]
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


# --------------------------------------------------- .pre-commit-config.yaml


def _precommit(root: Path, profile: ToolProfile, files: list[Path]) -> str:
    langs = set(profile.languages)
    exts = {p.suffix for p in files}
    ruff = "Ruff" in profile.formatters or "Ruff" in profile.linters
    black = "Black" in profile.formatters
    prettier = "Prettier" in profile.formatters

    lines = [
        "# Generated by ConventionGuardian (cg init-styleguide). Review before committing.",
        "# Install: pre-commit install && pre-commit run --all-files",
        "default_language_version:",
        "  python: python3",
        "repos:",
        "  - repo: https://github.com/pre-commit/pre-commit-hooks",
        "    rev: v5.0.0  # bump to taste",
        "    hooks:",
        "      - id: trailing-whitespace",
        "      - id: end-of-file-fixer",
        "      - id: mixed-line-endings",
        "        args: [--fix=lf]",
    ]
    if (root / "pyproject.toml").is_file():
        lines.append("      - id: check-toml")
    if exts & {".yaml", ".yml"}:
        lines.append("      - id: check-yaml")
    if ".json" in exts:
        lines.append("      - id: check-json")

    if ruff:
        v = _detect_version("ruff")
        rev = f"v{v}" if v else "REPLACE-ME"
        note = f"  # detected ruff {v}" if v else "  # ruff not on PATH; pin your version"
        lines += [
            "  - repo: https://github.com/astral-sh/ruff-pre-commit",
            f"    rev: {rev}{note}",
            "    hooks:",
            "      - id: ruff",
            "        args: [--fix]",
            "      - id: ruff-format",
        ]
    elif black:
        v = _detect_version("black")
        lines += [
            "  - repo: https://github.com/psf/black",
            f"    rev: {v or 'REPLACE-ME'}  # pin your black version",
            "    hooks:",
            "      - id: black",
        ]
    elif "Python" in langs:
        lines += [
            "  # cg: no Python formatter detected; add one, e.g.:",
            "  # - repo: https://github.com/astral-sh/ruff-pre-commit",
            "  #   rev: v0.0.0",
            "  #   hooks:",
            "  #     - id: ruff",
            "  #     - id: ruff-format",
        ]

    if prettier:
        lines += [
            "  - repo: https://github.com/pre-commit/mirrors-prettier",
            "    rev: v3.1.0  # mirror is archived; pin your prettier version",
            "    hooks:",
            "      - id: prettier",
        ]
    if "Go" in langs:
        lines += [
            "  - repo: local",
            "    hooks:",
            "      - id: gofmt",
            "        name: gofmt",
            "        entry: gofmt -w",
            "        language: system",
            "        types: [go]",
        ]
    if "Rust" in langs:
        lines += [
            "  - repo: local",
            "    hooks:",
            "      - id: rustfmt",
            "        name: rustfmt",
            "        entry: rustfmt --edition 2021  # adjust edition",
            "        language: system",
            "        types: [rust]",
        ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------- .cg/ci-lint.yml --


def _ci(profile: ToolProfile, files: list[Path]) -> str:
    langs = set(profile.languages)
    steps: list[str] = ["      - uses: actions/checkout@v4"]

    if "Python" in langs:
        steps += [
            "      - uses: actions/setup-python@v5",
            "        with:",
            '          python-version: "3.x"',
        ]
        if "Ruff" in profile.formatters or "Ruff" in profile.linters:
            steps += [
                "      - run: pip install ruff",
                "      - run: ruff check .",
                "      - run: ruff format --check .",
            ]
        if "mypy" in profile.linters:
            steps += ["      - run: pip install mypy", "      - run: mypy ."]
        if "pytest" in profile.tests:
            steps += [
                "      # adjust install for your dependency manager",
                "      - run: pip install pytest",
                "      - run: pytest -q",
            ]
    if langs & {"JavaScript", "TypeScript"}:
        has_lock = any(p.name == "package-lock.json" for p in files)
        steps += [
            "      - uses: actions/setup-node@v4",
            "        with:",
            "          node-version: 20",
            f"      - run: {'npm ci' if has_lock else 'npm install'}",
        ]
        if "ESLint" in profile.linters:
            steps.append("      - run: npx eslint .")
        if "Prettier" in profile.formatters:
            steps.append("      - run: npx prettier --check .")
        if any(t in profile.tests for t in ("Jest", "Vitest")):
            steps.append("      - run: npm test --if-present")
    if "Go" in langs:
        steps += [
            "      - uses: actions/setup-go@v5",
            "        with:",
            "          go-version-file: go.mod",
            '      - run: test -z "$(gofmt -l .)"  # unformatted files fail the job',
            "      - run: go vet ./...",
            "      - run: go test ./...",
        ]
        if "golangci-lint" in profile.linters:
            steps.append("      - uses: golangci/golangci-lint-action@v6")
    if "Rust" in langs:
        steps.append("      - uses: dtolnay/rust-toolchain@stable")
        if "rustfmt" in profile.formatters:
            steps.append("      - run: cargo fmt --all -- --check")
        if "Clippy" in profile.linters:
            steps.append("      - run: cargo clippy -- -D warnings")
        steps.append("      - run: cargo test")

    steps += [
        "      # ConventionGuardian: audit is informational (exit 0); verify exits non-zero on failure.",
        "      - run: pip install convention-guardian",
        "      - run: cg audit",
        "      - run: cg verify",
    ]
    header = [
        "# Generated by ConventionGuardian (cg init-styleguide).",
        "# Copy into .github/workflows/ (e.g. .github/workflows/cg-lint.yml) to arm it.",
        "name: cg-lint",
        '"on":',
        "  push:",
        "  pull_request:",
        "",
        "jobs:",
        "  lint:",
        "    runs-on: ubuntu-latest",
        "    steps:",
    ]
    return "\n".join(header + steps) + "\n"


# ------------------------------------------------------------ STYLEGUIDE.md -


def _styleguide_md(
    root: Path, findings: list[Finding], profile: ToolProfile, files: list[Path]
) -> str:
    langs = profile.languages
    has_js = bool({"JavaScript", "TypeScript"} & set(langs))
    fmt_of_record = ", ".join(profile.formatters) if profile.formatters else "none detected (cg built-in rules apply)"
    linters = ", ".join(profile.linters) if profile.linters else "none detected"
    tests = ", ".join(profile.tests) if profile.tests else "none detected"

    n_find = len(findings)
    n_app = sum(1 for f in findings if not f.review_only())
    crlf = _files_with(findings, "misc-crlf")
    tabs = _files_with(findings, "fmt-tabs")
    fnl = _files_with(findings, "fmt-final-newline")
    long_lines = _files_with(findings, "fmt-long-lines")
    imp_files = len({f.path for f in findings if f.category == Category.IMPORTS})
    qfind = [f for f in findings if f.fix_id in ("fmt-quotes", "js-quotes")]
    qfiles = {f.path for f in qfind}
    qdir = _quote_direction(qfind)
    naming = [f for f in findings if f.category == Category.NAMING]
    docs = [f for f in findings if f.category == Category.DOCS]

    out: list[str] = [
        f"# Style Guide — {root.name}",
        "",
        f"_Generated by ConventionGuardian (`cg init-styleguide`) on {date.today().isoformat()}. "
        f"Derived from an audit of {len(files)} files: {n_find} findings "
        f"({n_app} auto-fixable, {n_find - n_app} manual review)._",
        "",
        "## Stack",
        "",
        "| | |",
        "|---|---|",
        f"| Languages | {', '.join(langs) if langs else '—'} |",
        f"| Formatter of record | {fmt_of_record} |",
        f"| Linters | {linters} |",
        f"| Tests | {tests} |",
        "",
        "## Conventions",
        "",
        "### Whitespace & line endings",
        "",
        "- UTF-8; LF line endings; one trailing newline at EOF; no trailing whitespace.",
    ]
    if crlf:
        out.append(f"- Drift: {crlf} file(s) still CRLF (batch: `cg apply --batch misc`).")
    if fnl:
        out.append(f"- Drift: {fnl} file(s) missing a final newline (batch: formatting).")

    out += ["", "### Indentation", ""]
    if "Python" in langs:
        out.append("- Python: 4 spaces (soft limit 100 columns).")
    if has_js:
        out.append("- JS/TS: 2 spaces.")
    if "Go" in langs:
        out.append("- Go: tabs (gofmt owns Go formatting).")
    if "Rust" in langs:
        out.append("- Rust: 4 spaces (rustfmt).")
    if tabs:
        out.append(f"- Drift: {tabs} file(s) with tab indentation in space-indented Python (batch: formatting).")

    out += ["", "### Strings", ""]
    out.append(f"- {qdir or 'Double quotes'} are the majority convention; stay consistent.")
    if qfiles:
        out.append(f"- Drift: {len(qfiles)} file(s) with mixed quote styles (batch: formatting).")

    out += [
        "",
        "### Imports",
        "",
        "- Order: standard library → third-party → local, blank line between groups; "
        "one module per `import` statement.",
    ]
    if imp_files:
        out.append(f"- Drift: {imp_files} file(s) out of order (batch: imports).")

    out += [
        "",
        "### Naming",
        "",
        "- Python: snake_case for functions, variables and modules; PascalCase for classes.",
        "- JS/TS: camelCase for variables and functions; PascalCase for types and React components.",
        "- Go/Rust: exported names are public API — cg never renames them.",
    ]
    if naming:
        n_app_naming = sum(1 for f in naming if not f.review_only())
        out.append(
            f"- Drift: {len(naming)} naming finding(s), {n_app_naming} auto-fixable (batch: naming)."
        )

    out += [
        "",
        "### Docs",
        "",
        "- Docstrings and comments are report-only: cg never rewrites prose.",
    ]
    if docs:
        out.append(f"- {len(docs)} docs finding(s) in the current audit (batch: docs).")

    if long_lines:
        out.append("")
        out.append(f"- Line-length drift: {long_lines} file(s) over 100 columns; wrapping is manual review (strings).")

    out += [
        "",
        "### Policy",
        "",
        "- Findings with confidence < 100 are manual-review only and are never auto-applied.",
        "- Fixes are deterministic and zero-logic-change; every apply runs verification and auto-reverts on failure.",
        "",
        "## Audit snapshot",
        "",
        "| Category | Findings | Auto-fixable | Manual review |",
        "|---|---:|---:|---:|",
    ]
    total_f = total_a = 0
    for cat in Category:
        fs = [f for f in findings if f.category == cat]
        if not fs:
            continue
        a = sum(1 for f in fs if not f.review_only())
        total_f += len(fs)
        total_a += a
        out.append(f"| {cat.value} | {len(fs)} | {a} | {len(fs) - a} |")
    out += [
        f"| **total** | {total_f} | {total_a} | {total_f - total_a} |",
        "",
        "## Enforcement",
        "",
        "1. `cg audit` — full report; never writes.",
        "2. `pre-commit run --all-files` — hygiene hooks from `.pre-commit-config.yaml`.",
        "3. `cg apply --batch safe` (or `--ids ...`) — branch `cg/convention-<ts>`, verify, auto-revert on failure.",
        "4. CI: copy `.cg/ci-lint.yml` into `.github/workflows/`.",
        "",
    ]
    return "\n".join(out)


# ------------------------------------------------------------------ build ---


def build_styleguide(
    root: Path,
    findings: list[Finding],
    profile: ToolProfile,
    files: list[Path],
) -> StyleguidePlan:
    """Derive the four artifacts from the current audit; no I/O writes here."""
    root = Path(root)
    plan = StyleguidePlan()
    plan.artifacts[".editorconfig"] = _editorconfig(profile, files, findings)
    plan.artifacts[".pre-commit-config.yaml"] = _precommit(root, profile, files)
    plan.artifacts[".cg/ci-lint.yml"] = _ci(profile, files)
    plan.artifacts["STYLEGUIDE.md"] = _styleguide_md(root, findings, profile, files)
    plan.existed = {rel: (root / rel).exists() for rel in plan.artifacts}

    n_app = sum(1 for f in findings if not f.review_only())
    fmt = ", ".join(profile.formatters) if profile.formatters else "none detected"
    plan.notes = [
        f"Audit basis: {len(findings)} findings ({n_app} auto-fixable) across {len(files)} files",
        f"Formatter of record: {fmt}",
        "CI snippet is .cg/ci-lint.yml — copy into .github/workflows/ to arm it",
    ]
    return plan


def write_styleguide(
    root: Path, plan: StyleguidePlan, force: bool = False
) -> tuple[list[str], list[str]]:
    """Write plan artifacts (LF endings); skip existing files unless force."""
    written: list[str] = []
    skipped: list[str] = []
    for rel, content in plan.artifacts.items():
        target = root / rel
        if target.exists() and not force:
            skipped.append(rel)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8", newline="\n")
        written.append(rel)
    return written, skipped


# ------------------------------------------------------------------ check ---

# The generation date in STYLEGUIDE.md must not read as drift the next day.
_GENERATED_STAMP_RE = re.compile(
    r"(Generated by ConventionGuardian \(`?cg init-styleguide`?\)) on \d{4}-\d{2}-\d{2}"
)


def _mask_stamp(text: str) -> str:
    return _GENERATED_STAMP_RE.sub(r"\1 on <date>", text)


def _tracked_files(root: Path) -> set[str] | None:
    """Git-tracked files (posix rel paths); None when not a git repo."""
    try:
        res = subprocess.run(
            ["git", "-C", str(root), "ls-files"],
            capture_output=True, text=True, encoding="utf-8", errors="replace",
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if res.returncode != 0:
        return None
    return set(res.stdout.splitlines())


def check_styleguide(root: Path, plan: StyleguidePlan) -> DriftReport:
    """Compare regenerated artifacts against the files on disk (no writes).

    Only git-tracked artifacts are checked — committing (or staging) an
    artifact "arms" it; missing or untracked ones are reported as not armed
    and do not fail the run. Comparison normalizes CRLF (Windows autocrlf
    checkouts) and masks the generation date stamp, so neither counts as
    drift; any other difference does.
    """
    root = Path(root)
    tracked = _tracked_files(root)
    rep = DriftReport()
    for rel, content in plan.artifacts.items():
        target = root / rel
        if not target.is_file() or (tracked is not None and rel not in tracked):
            rep.not_armed.append(rel)
            continue
        current = _mask_stamp(
            target.read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n")
        )
        if current == _mask_stamp(content):
            rep.ok.append(rel)
        else:
            rep.drifted.append(rel)
            rep.diffs[rel] = unified_diff(_mask_stamp(content), current, Path(rel))
    return rep
